name: Build JAR

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Steup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install SBT
        run: |
          sudo apt-get update
          sudo apt-get install -y sbt

      - name: Build with SBT
        run: sbt package