name: Build JAR

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Steup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install SBT
        run: |
          curl -L https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt > sbt
          chmod +x sbt
          sudo mv sbt /usr/local/bin/sbt

      - name: Check SBT
        run: sbt --version

      - name: Build with SBT
        run: sbt package