name: Build JAR

on:
  push:
env:
  IMAGE_NAME: ghcr.io/hamzakhammassi/filesreorg:latest

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Steup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: sbt

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Build with SBT
        run: sbt -v package

      - name: Prepare JAR for Docker
        run: |
          JAR=$(find target -type f -name "*.jar" | head -n 1)
          cp "$JAR" app.jar

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/**/*.jar

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: |
          docker push IMAGE_NAME